CREATE DATABASE PROJECT30;

USE PROJECT30;


CREATE TABLE USER_TABLE(
USERS_ID INT IDENTITY(5555,1) PRIMARY KEY  , 
USER_FULLNAME VARCHAR(255) ,
USER_EMAIL VARCHAR(255) , 
USER_PHONE BIGINT , 
USER_ADDRESS VARCHAR(255) , 
USER_CITY VARCHAR(255),
USER_STATE VARCHAR(255),
USER_POSTAL_CODE BIGINT ,
USER_REGISTRATION_DATE DATE , 

)

INSERT INTO USER_TABLE(USER_FULLNAME,USER_EMAIL,USER_PHONE,USER_ADDRESS,USER_CITY,USER_STATE,USER_POSTAL_CODE,USER_REGISTRATION_DATE)
VALUES('John Doe', 'john.doe@example.com', 1234567890, '123 Main St', 'City A', 'State X', 12345, '2023-08-30')


